

version: 0.2

phrases:
  install:
    runtime-versions:
      nodejs: 14

    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
```
    